# Generated by Django 5.2.1 on 2025-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_asignacion_plan_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacion",
            name="estado",
            field=models.CharField(
                choices=[("PENDIENTE", "Pendiente"), ("PAGADO", "Pagado")],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
