# Generated by Django 5.2.1 on 2025-05-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_asignacion_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                (
                    "email_comprador",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("estado_pago", models.CharField(default="PENDIENTE", max_length=20)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
            ],
        ),
    ]
