# Generated by Django 5.2.1 on 2025-05-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="costo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
