# Generated by Django 5.2.1 on 2025-05-21 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_producto_costo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_distribuidor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_publico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_revendedor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DISTRIBUIDOR", "Distribuidor"),
                    ("REVENDEDOR", "Revendedor"),
                ],
                default="DISTRIBUIDOR",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Revendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribuidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revendedores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revendedor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
