# Generated by Django 5.2.1 on 2025-05-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_producto_precio_producto_precio_distribuidor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="dni",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="domicilio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="provincia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
